# ==========================================================
# Module Name         : stores
# Project             : Test Data Generator
# Purpose             : store master data
# Author              : TheVRD
# Created Date        : 2026-07-04
# Version             : 1.0
# ==========================================================


from test_data_generator.models.store import Store

STORES = (
    Store("STR00001", "Ambience Mall", "Gurgaon", "Haryana"),
    Store("STR00002", "DLF CyberHub", "Gurgaon", "Haryana"),
    Store("STR00003", "Phoenix Marketcity", "Mumbai", "Maharashtra"),
    Store("STR00004", "R City Mall", "Mumbai", "Maharashtra"),
    Store("STR00005", "High Street Phoenix", "Mumbai", "Maharashtra"),
    Store("STR00006", "Lulu Mall", "Lucknow", "Uttar Pradesh"),
    Store("STR00007", "Phoenix Palassio", "Lucknow", "Uttar Pradesh"),
    Store("STR00008", "Select Citywalk", "New Delhi", "Delhi"),
    Store("STR00009", "DLF Promenade", "New Delhi", "Delhi"),
    Store("STR00010", "Pacific Mall", "New Delhi", "Delhi"),
    Store("STR00011", "VR Bengaluru", "Bengaluru", "Karnataka"),
    Store("STR00012", "Orion Mall", "Bengaluru", "Karnataka"),
    Store("STR00013", "Phoenix Marketcity", "Bengaluru", "Karnataka"),
    Store("STR00014", "Forum South Bengaluru", "Bengaluru", "Karnataka"),
    Store("STR00015", "Inorbit Mall", "Hyderabad", "Telangana"),
    Store("STR00016", "Sarath City Capital Mall", "Hyderabad", "Telangana"),
    Store("STR00017", "GVK One Mall", "Hyderabad", "Telangana"),
    Store("STR00018", "Nexus Hyderabad", "Hyderabad", "Telangana"),
    Store("STR00019", "Express Avenue", "Chennai", "Tamil Nadu"),
    Store("STR00020", "Phoenix Marketcity", "Chennai", "Tamil Nadu"),
    Store("STR00021", "VR Chennai", "Chennai", "Tamil Nadu"),
    Store("STR00022", "Brookefields Mall", "Coimbatore", "Tamil Nadu"),
    Store("STR00023", "Lulu Mall", "Kochi", "Kerala"),
    Store("STR00024", "Centre Square Mall", "Kochi", "Kerala"),
    Store("STR00025", "Sobha City Mall", "Thrissur", "Kerala"),
    Store("STR00026", "Forum Mall", "Kochi", "Kerala"),
    Store("STR00027", "City Centre", "Kolkata", "West Bengal"),
    Store("STR00028", "South City Mall", "Kolkata", "West Bengal"),
    Store("STR00029", "Quest Mall", "Kolkata", "West Bengal"),
    Store("STR00030", "Acropolis Mall", "Kolkata", "West Bengal"),
    Store("STR00031", "Elante Mall", "Chandigarh", "Chandigarh"),
    Store("STR00032", "VR Punjab", "Mohali", "Punjab"),
    Store("STR00033", "North Country Mall", "Mohali", "Punjab"),
    Store("STR00034", "AlphaOne Mall", "Amritsar", "Punjab"),
    Store("STR00035", "Ahmedabad One Mall", "Ahmedabad", "Gujarat"),
    Store("STR00036", "Palladium Ahmedabad", "Ahmedabad", "Gujarat"),
    Store("STR00037", "Iscon Mega Mall", "Ahmedabad", "Gujarat"),
    Store("STR00038", "RahulRaj Mall", "Surat", "Gujarat"),
    Store("STR00039", "Inorbit Mall", "Vadodara", "Gujarat"),
    Store("STR00040", "DB City Mall", "Bhopal", "Madhya Pradesh"),
    Store("STR00041", "C21 Mall", "Indore", "Madhya Pradesh"),
    Store("STR00042", "Treasure Island", "Indore", "Madhya Pradesh"),
    Store("STR00043", "Phoenix Citadel", "Indore", "Madhya Pradesh"),
    Store("STR00044", "Z Square Mall", "Kanpur", "Uttar Pradesh"),
    Store("STR00045", "Wave Mall", "Lucknow", "Uttar Pradesh"),
    Store("STR00046", "Shipra Mall", "Ghaziabad", "Uttar Pradesh"),
    Store("STR00047", "The Great India Place", "Noida", "Uttar Pradesh"),
    Store("STR00048", "DLF Mall of India", "Noida", "Uttar Pradesh"),
    Store("STR00049", "Logix City Center", "Noida", "Uttar Pradesh"),
    Store("STR00050", "Vegas Mall", "Dwarka", "Delhi"),
    Store("STR00051", "Viviana Mall", "Thane", "Maharashtra"),
    Store("STR00052", "Korum Mall", "Thane", "Maharashtra"),
    Store("STR00053", "Seawoods Grand Central", "Navi Mumbai", "Maharashtra"),
    Store("STR00054", "Nexus Seawoods", "Navi Mumbai", "Maharashtra"),
    Store("STR00055", "Amanora Mall", "Pune", "Maharashtra"),
    Store("STR00056", "Phoenix Marketcity", "Pune", "Maharashtra"),
    Store("STR00057", "Westend Mall", "Pune", "Maharashtra"),
    Store("STR00058", "Nexus Westend", "Pune", "Maharashtra"),
    Store("STR00059", "Prozone Mall", "Aurangabad", "Maharashtra"),
    Store("STR00060", "Empress Mall", "Nagpur", "Maharashtra"),
    Store("STR00061", "VR Nagpur", "Nagpur", "Maharashtra"),
    Store("STR00062", "City Centre", "Nashik", "Maharashtra"),
    Store("STR00063", "Lulu Mall", "Thiruvananthapuram", "Kerala"),
    Store("STR00064", "Cosmopolitan Mall", "Bhubaneswar", "Odisha"),
    Store("STR00065", "Esplanade One", "Bhubaneswar", "Odisha"),
    Store("STR00066", "DN Regalia", "Bhubaneswar", "Odisha"),
    Store("STR00067", "Nucleus Mall", "Ranchi", "Jharkhand"),
    Store("STR00068", "Spring City Mall", "Ranchi", "Jharkhand"),
    Store("STR00069", "P&M Mall", "Patna", "Bihar"),
    Store("STR00070", "City Centre", "Patna", "Bihar"),
    Store("STR00071", "City Centre Mall", "Siliguri", "West Bengal"),
    Store("STR00072", "Orbit Mall", "Siliguri", "West Bengal"),
    Store("STR00073", "Central Mall", "Jaipur", "Rajasthan"),
    Store("STR00074", "World Trade Park", "Jaipur", "Rajasthan"),
    Store("STR00075", "Pink Square Mall", "Jaipur", "Rajasthan"),
    Store("STR00076", "Elements Mall", "Jaipur", "Rajasthan"),
    Store("STR00077", "Celebration Mall", "Udaipur", "Rajasthan"),
    Store("STR00078", "Ashima Mall", "Bhopal", "Madhya Pradesh"),
    Store("STR00079", "Magneto Mall", "Raipur", "Chhattisgarh"),
    Store("STR00080", "City Centre Mall", "Raipur", "Chhattisgarh"),
    Store("STR00081", "City Centre", "Mangalore", "Karnataka"),
    Store("STR00082", "Forum Fiza Mall", "Mangalore", "Karnataka"),
    Store("STR00083", "Mall of Mysore", "Mysuru", "Karnataka"),
    Store("STR00084", "Garuda Mall", "Bengaluru", "Karnataka"),
    Store("STR00085", "Nexus Koramangala", "Bengaluru", "Karnataka"),
    Store("STR00086", "Forum Sujana Mall", "Hyderabad", "Telangana"),
    Store("STR00087", "Manjeera Mall", "Hyderabad", "Telangana"),
    Store("STR00088", "Orbit Mall", "Ajmer", "Rajasthan"),
    Store("STR00089", "Goldighi Mall", "Siliguri", "West Bengal"),
    Store("STR00090", "Raghuleela Mall", "Vashi", "Maharashtra"),
    Store("STR00091", "DB City Mall", "Gwalior", "Madhya Pradesh"),
    Store("STR00092", "Central Mall", "Visakhapatnam", "Andhra Pradesh"),
    Store("STR00093", "CMR Central", "Visakhapatnam", "Andhra Pradesh"),
    Store("STR00094", "LEPL Centro", "Vijayawada", "Andhra Pradesh"),
    Store("STR00095", "PVP Square", "Vijayawada", "Andhra Pradesh"),
    Store("STR00096", "City Centre Mall", "Nashik", "Maharashtra"),
    Store("STR00097", "Omaxe Mall", "Faridabad", "Haryana"),
    Store("STR00098", "Crown Interiorz Mall", "Faridabad", "Haryana"),
    Store("STR00099", "MBD Neopolis", "Ludhiana", "Punjab"),
    Store("STR00100", "Pavilion Mall", "Ludhiana", "Punjab"),
)
